title: Yannick San-A-Jong
email: yannick@sanajo.ng
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://yannicksanajong.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter: yannicksanajong
github:  ysanajong
linkedin: yannicksanajong
goodreads: ysan
youtube: yannicksanajong
instagram: ysanajong

# Build settings
theme: minima
# theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
    vendor/ruby/